# Generated by Django 5.1.2 on 2024-12-04 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
